# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/tools/Senparc.Weixin.CLI/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: 'Use .NET SDK 6'
  inputs:
    version: '6.0.x'
    packageType: 'sdk'

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'


# - task: VSBuild@1
#   inputs:
#     solution: '$(solution)'
#     msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'


- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'config'
    externalFeedCredentials: 'Nuget-V3-SupportSymbol'
   
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '$(solution)'
    arguments: '--configuration Release'

- task: NuGetCommand@2
  displayName: Senparc.Weixin.CLI
  inputs:
    command: push
    packagesToPush: '**/Weixin.*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: 'Nuget-V3-SupportSymbol'
  continueOnError: true
  condition: succeededOrFailed()


- task: NuGetCommand@2
  displayName: Senparc.WeChat.CLI
  inputs:
    command: push
    packagesToPush: '**/WeChat.*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: 'Nuget-V3-SupportSymbol'
  continueOnError: true
  condition: succeededOrFailed()


# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
