<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Version>1.0.1</Version>
		<PackageReleaseNotes>
		  [2026-07-23] v1.0.1 升级小程序示例依赖
		  1、升级 AspNet、TenPayV3、WxOpen 与 WxOpen.Middleware 至最新稳定版
		  2、适配最新小程序及微信支付能力
		</PackageReleaseNotes>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- 此节点为 Sample 共享文件需要而添加，实际项目无需添加 -->
		<GenerateEmbeddedFilesManifest Condition=" '$(Configuration)' != 'Release' ">true</GenerateEmbeddedFilesManifest>
	</PropertyGroup>

	<!-- 此节点为 Sample 共享文件需要而添加，实际项目无需添加 -->
	<ItemGroup Condition=" '$(Configuration)' != 'Release' ">
		<PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
		<PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="8.0.0" />
		<!--<EmbeddedResource Include="..\..\Shared\Senparc.Weixin.Sample.Shared\wwwroot\**\*">
			<Link>wwwroot\%(RecursiveDir)/%(FileName)%(Extension)</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>-->
		<EmbeddedResource Include="wwwroot\**\*" />
	</ItemGroup>

	<!-- 此节点为 Sample 共享文件需要而添加，实际项目无需添加 -->
	<Import Project="..\..\Shared\Senparc.Weixin.Sample.Shared\Senparc.Weixin.Sample.Shared.projitems" Label="Shared" />

	<!--引用 Nuget 包-->
	<ItemGroup>
		<PackageReference Include="Senparc.Weixin.AspNet" Version="1.6.4" />
		<PackageReference Include="Senparc.Weixin.TenPayV3" Version="2.5.0" />
		<PackageReference Include="Senparc.Weixin.WxOpen" Version="3.28.0" />
		<PackageReference Include="Senparc.Weixin.WxOpen.Middleware" Version="1.5.3" />
	</ItemGroup>

	<!--直接引用源码-->
	<!--<ItemGroup>
		<ProjectReference Include="..\..\..\src\Senparc.Weixin.AspNet\Senparc.Weixin.AspNet.net10.csproj" />
		<ProjectReference Include="..\..\..\src\Senparc.Weixin.WxOpen.Middleware\Senparc.Weixin.WxOpen.Middleware.net10.csproj" />
		<ProjectReference Include="..\..\..\src\Senparc.Weixin.WxOpen\src\Senparc.Weixin.WxOpen\Senparc.Weixin.WxOpen\Senparc.Weixin.WxOpen.net10.csproj" />
	</ItemGroup>-->

</Project>
